FROM ubuntu:24.04
SHELL ["/bin/bash", "-l", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update

# sudo と最低限のツール
RUN apt-get install -y apt-utils
RUN apt-get install -y \
    sudo \
    curl wget git 

# 固定ユーザーを作成
WORKDIR /root/
RUN apt install -y nano

# Python
RUN apt-get install -y python3 python3-pip
RUN apt-get install python3.12-venv -y
RUN python3 -m venv /root/venv
RUN /root/venv/bin/pip install --upgrade pip
RUN /root/venv/bin/pip install sortedcontainers
RUN /root/venv/bin/pip install line-profiler
RUN /root/venv/bin/pip install sphinx
RUN /root/venv/bin/pip install sphinx-book-theme
ENV PATH="/root/venv/bin:${PATH}"


# PyPy
RUN apt-get install -y pypy3 pypy3-venv
RUN pypy3 -m venv /root/pypy-venv
RUN /root/pypy-venv/bin/pip install --upgrade pip
RUN /root/pypy-venv/bin/pip install sortedcontainers
ENV PATH="/root/pypy-venv/bin:${PATH}"

RUN apt-get install -y build-essential
RUN apt-get install -y gdb=12.1

RUN apt-get install -y clang-format
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git config --global user.name "Lit-to"
RUN git config --global user.email "litto0315@gmail.com"
RUN git config --global fetch.prune true

# rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN git clone https://github.com/Lit-to/atcoder.git /root/atcoder
COPY .bashrc /root/.bashrc
RUN git clone https://github.com/atcoder/ac-library.git /root/acl


# docker build -t atcoder .
# docker start -ai atcoder
