version: "3.9"
services:
  app:
    build: 
      context: ./deploykit
      dockerfile: ./dockerfile
    container_name: atcoder
    ports:
      - "2000:2000"
    volumes:
      - .:/root/atcoder:rw
    tty: true
    stdin_open: true
    command: ["/bin/bash"]