FROM ubuntu:latest
SHELL ["/bin/bash", "-l", "-c"]

ENV DEBIAN_FRONTEND=noninteractive


# sudo と最低限のツール
RUN apt-get update && apt-get install -y apt-utils
RUN apt-get update && apt-get install -y \
    sudo \
    curl wget git 

# 固定ユーザーを作成
WORKDIR /home/root/
RUN sudo apt-get update && sudo apt-get install -y nano

RUN sudo apt-get update && sudo apt-get install -y pypy3
RUN sudo apt-get update && sudo apt-get install -y python3 python3-pip
RUN sudo apt install python3.12-venv -y
# Python3 と pip は既にインストール済み
RUN python3 -m venv ~/venv \
    && ~/venv/bin/pip install --upgrade pip \
    && ~/venv/bin/pip install sortedcontainers && ~/venv/bin/pip install line-profiler && ~/venv/bin/pip install sphinx && ~/venv/bin/pip install sphinx-book-theme

# 環境変数 PATH に venv を追加
ENV PATH="~/venv/bin:${PATH}"

RUN sudo apt-get update && sudo apt-get install -y build-essential
RUN sudo apt-get update && sudo apt-get install -y gdb
RUN sudo apt install clang-format

ENV PATH="/usr/bin:${PATH}"
RUN sudo apt install -y clang-format

ENV PATH="/usr/bin:${PATH}"
RUN sudo apt install -y clang-format
RUN sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*

RUN git config --global user.name "Lit-to"
RUN git config --global user.email "litto0315@gmail.com"

RUN git clone https://github.com/Lit-to/atcoder.git ~/atcoder
COPY .profile ~/.profile
COPY .profile ~/.profile
COPY .bashrc ~/.bashrc
RUN git clone https://github.com/atcoder/ac-library.git ~/acl

RUN git clone https://github.com/atcoder/ac-library.git ~/acl

# docker build -t atcoder .
# docker start -ai atcoder
